blong/urls.py
from django.urls import path

from .views import *

app_name = 'blong'


urlpatterns = [
	path('',listar_publicaciones, name='listar_publicaciones'),
	path('<uuid:pub>/',ver_publicacion, name='ver_publicacion'),
	path('categoria/<int:categoria>/', ver_publicaciones_categoria, name='ver_publicaciones_categoria')
]

blong/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid


class Categoria(models.Model):
	descripcion = models.CharField(max_length=60,
							 		help_text='Descripcion de la categoria')
	autor = models.ForeignKey(User,
									on_delete=models.PROTECT,
									help_text='selecione el autor de la categoria')
	def __str__(self):
		return self.descripcion

class Publicacion(models.Model):
	id = models.UUIDField(primary_key= True, editable=False,  default=uuid.uuid4)
	titulo = models.CharField(max_length=200,
											help_text='escriba el titulo de la Publicacion')
	contenido = models.TextField(max_length=20000,
											help_text='escriba el contenido de la Publicacion')
	autor = models.ForeignKey(User,
								on_delete=models.PROTECT,
								help_text='seleccione el autor de la categoria')
	f_pub = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicacion')
	categorias = models.ManyToManyField(Categoria,
										help_text='selccione las categorias')
	def __str__(self):
		return self.titulo

	class Meta:
		verbose_name = 'Publicacion'
		verbose_name_plural = 'Publicaciones'
		ordering = ['-f_pub']


blong/views.py
from django.shortcuts import render

from .models import *


def listar_publicaciones(request):
	news = Publicacion.objects.all().order_by('-f_pub')
	return render(request,'./post/index.html',{'news':news})


def ver_publicacion(request, pub):
	publicacion = Publicacion.objects.get(id= pub)
	return render(request, './post/ver.html',{'pub':publicacion})


def ver_publicaciones_categoria(request, categoria):
	categoria = categoria.objects.get(id= categoria)
	return render(request,'/post/index.html',{'categoria':categoria})

blong/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
	<title>{% block titulo %}DISEÑO WEB{% endblock %}</title>
	<!-- compliend and minified css-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body background="https://embed-fastly.wistia.com/deliveries/d666777da0b34facc71d000b4d93613a.webp?image_crop_resized=960x480">

	<!--compiled and minified JavaScript -->
	<nav>
		<div class="nav-wrapper #263238 blue-grey darken-4">
			<a href="{% url 'blong:listar_publicaciones'  %}" class="brand-logo" style="fonst-weight: 43" >DiseñoWeb</a>
			<a href="#" data-target="menu-chico" class="sidenav-trigger"><i class="material-icons">menu</i></a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><a href="{% url 'blong:listar_publicaciones'  %}">Programador</a></li>
				<li><a href="{% url 'blong:listar_publicaciones'  %}">Analista</a></li>
				<li><a href="{% url 'blong:listar_publicaciones'  %}">Diseñador</a></li>
				<li><a href="{% url 'blong:listar_publicaciones'  %}">graficas</a></li>
			</ul>
		</div>
	</nav>
		<div>
			<a class='dropdown-trigger btn' href='#' data-target='dropdown1'>Listar Diseñadores</a>
			<ul id='dropdown1' class='dropdown-content'>
			    <li><a href="#!">one</a></li>
			    <li><a href="#!">two</a></li>
			    <li class="divider" tabindex="-1"></li>
			    <li><a href="#!">three</a></li>
			    <li><a href="#!"><i class="material-icons">view_module</i>four</a></li>
			    <li><a href="#!"><i class="material-icons">cloud</i>five</a></li>
 			 </ul>
 		</div>

	<div class="container" style="padding-bottom:2em; ">

		{% block cuerpo %}

		{% endblock %}
	</div>

	
	<div class="parallax-container">
		<div class="parallax">
			<img src="https://thesocialmediafamily.com/wp-content/uploads/2018/01/diseno-web-profesional-1200x900.jpg" alt="">	
		</div>
	</div>
		<video class="responsive-video" controls >
			<source src="https://youtu.be/m7lF65ZBgOM" type="https://youtu.be/m7lF65ZBgOM">
		</video>
	</div>

	<footer class="page-footer teal darken-2">
		<div align="center" style="padding:zem;">
			<p>Sitio creado por Manuel H</p> 
			<p align="center"> Graciar por tu visita</p>
			
		</div>
	</footer>

</body>
	<!--complied and minified javascript -->
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script async src="https://static.addtoany.com/menu/page.js"></script>
	
	<script>
		document.addEventistener('DCFIContinoaeded'.function() {
				M.mutoInit():
				});
	</script>
</html>

blong/templates/post/index.html
{% extends "base.html" %}

{% block titulo %}|DISEÑO WEB{% endblock %}


{% block cuerpo %}
	{% if categoria %}
		<h1>publicaciones en {{ categoria.descripcion }}</h1>
		{% for new in categoria.publicacion_set.all %}
			<div >
				<h2><a href="{% url  'blong:ver_publicacion'  new.id %}">{{ new.titulo }}</a></h2><hr>
				<p>
				{{ new.contenido|truncatechars:250 }}<br>
				{{ new.autor.get_full_name }} publicado: {{ new.f_pub }}
				</p>
			</div>
		{% endfor %}
		{% for categoria in categoria %}
		<div class="nav-wrapper #ffffff blanco">
			<a href="{% url 'app:ver_post_categoria' categoria.id %}">
				<div class="chip">
					{{ categoria.descripcion }}
					<img class="responsive-img" src="cool_pic.jpg">
				</div>
			</a>
		</div>
		{% endfor %}
		
	{% else %}

		{% for new in news %}
			<div class="nav-wrapper #ffffff blanco">
				<h2><a href="{% url  'blong:ver_publicacion'  new.id %}">{{ new.titulo }}</a></h2><hr>

				<p>
					{{ new.contenido|truncatechars:250 }}<br>
					{{ new.autor.get_full_name }} publicado: {{ new.f_pub }}

					{% for categoria in new.categorias.all %}
						<div class="nav-wrapper #263238 blue-grey darken-4">
							<a href="{% url  'blong:ver_publicaciones_categoria'  categoria.id %}">{{categoria.descripcion}}</a>
						</div>
					{% endfor %}
				</p>
			</div>
		{% endfor %}
	{% endif %}

{% endblock %}


blong/templates/post/ver.html
{% extends 'base.html' %}

{% block titulo %} {{ publicacion.titulo|truncatechars:30 }}|DISEÑO WEB{% endblock %}

{% block cuerpo %}
	<body> 
	<h1>{{ publicacion.titulo }}</h1>
	<p align="justify">
		{{ publicacion.contenido }}
	</p>
	{{ publicacion.autor.get_full_name }} publicado: {{ publicacion.f_pub }}
		<div class="container">
	        <!-- Page Content goes here -->
		</div>
		<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
			<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
			<a class="a2a_button_facebook"></a>
			<a class="a2a_button_twitter"></a>
			<a class="a2a_button_email"></a>
			<a class="a2a_button_whatsapp"></a>
			<a class="a2a_button_pinterest"></a>
		</div>
	</body>

{% endblock %}